using Registry.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Registry.Controllers
{
    public class AllServicesController : ApiController
    {
        //To get all the services along with its details, the AllservicesController class is used.
        //The get method is used to write function description as we have to read the data from existing file.
        // GET: api/AllServices
        public List<Object> Get()
        {
            List<Object> output = new List<Object>();

            //if the file doesn't exist in the path, it will return "File doesn't exist" statement
            if (!File.Exists("d:\\status.txt"))
            {
                String error = "File doesnt' exist";
                output.Add(error);
                return output;
            }
            using (StreamReader sr = File.OpenText("d:\\status.txt"))
            {
                //Read all the lines and store it in ana array called lines
                string[] lines = File.ReadAllLines("d:\\status.txt");
                bool isMatch = false;

                //Loop is used to extract all the details appropriateley
                for (int x = 0; x < lines.Length-2 ; x++)
                {

                    //Returs the  detail in json output
                        var result = new { Name = lines[x], Description = lines[x + 1], Api_endpoint = lines[x + 2], number_of_operands = lines[x + 3], operand_type = lines[x + 4] };
                        //return Json(result, JsonRequestBehavior.AllowGet);
                        output.Add(result);

                        x = x + 4;
                       
                    
                }
            }
            //return the appropriate json output
            return output;
        }



        //Autogenerated functions which are not used for this project.
        /*
        // GET: api/AllServices/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/AllServices
        public void Post([FromBody] String value)
        {
           
        }

        // PUT: api/AllServices/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/AllServices/5
        public void Delete(int id)
        {
        }

        */
    }
}
