using Authenticator;
using ServiceProvider.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.ServiceModel;
using System.Web.Http;

namespace ServiceProvider.Controllers
{
    public class MulThreeNumbersController : ApiController
    {
      

        ServerInterface foob;

        // POST: api/MulThreeNumbers
        public Object Post([FromBody]MulThreeNumbersModel value)
        {
            ////the below set of code is used to call the validate function of the server interface.
            ChannelFactory<ServerInterface> foobFactory;

            //creates a client stub
            NetTcpBinding tcp = new NetTcpBinding();

            //Set the URL and create the connection!string
            var URL = "net.tcp://localhost:10108/Service1 ";
            foobFactory = new ChannelFactory<ServerInterface>(tcp, URL);
            foob = foobFactory.CreateChannel();
            //............................................................


            //The result of validation is stored in astring called "result"
            String result = foob.validate(value.id);
           
            if (result.Equals("Validated"))
            {
                //if the token validation is successful, the output will be displayed
                int sum = value.num1 * value.num2 * value.num3;
                var response = new { Answer = sum };
                return response;
            }
            else
            {
                //if validation is not successful
                var response = new { Status = "Denied", Reason = "Authentication Error" };
                return response;
            }

        }

        //the below codes are autogenerated functions which are not used in this project
        /*
        // GET: api/MulThreeNumbers
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/MulThreeNumbers/5
        public string Get(int id)
        {
            return "value";
        }
        // PUT: api/MulThreeNumbers/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/MulThreeNumbers/5
        public void Delete(int id)
        {
        }
        */
    }
}
